version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recomendacao
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

